
before_install:
  - psql --version
  - sudo service postgresql stop
  - sudo apt-get -y --purge remove postgresql libpq-dev libpq5 postgresql-client-common postgresql-common
  - sudo rm -rf /var/lib/postgresql
  - sudo apt-get update -qq
  - sudo apt-get -y install bc libpam-dev libedit-dev
  - git clone https://github.com/postgres/postgres.git /home/travis/postgres-dev
  - cd /home/travis/postgres-dev
  - git fetch origin REL9_6_STABLE
  - git checkout -b REL9_6_STABLE origin/REL9_6_STABLE
  - export POSTGRES_HOME=/home/travis/postgres-dev/pgsql/$PGVERSION
  - echo 'export POSTGRES_HOME=/home/travis/postgres-dev/pgsql/$PGVERSION' >> ~/.bashrc
  - ./configure --prefix=$POSTGRES_HOME
  - make -j 2
  - make install
  - echo 'export PATH=$PATH:$POSTGRES_HOME/bin' >> ~/.bashrc
  - export PATH=$PATH:$POSTGRES_HOME/bin

before_script:
  - mv /home/travis/build/ossc-db/pgaudit /home/travis/postgres-dev/contrib
  - cd /home/travis/postgres-dev/contrib/pgaudit && git describe --alway
  - make USE_PGXS=1
  - make USE_PGXS=1 install 
  
language: cpp
compiler:
  - gcc

branches:
  only:
  - refactored

script: make USE_PGXS=1 installcheck

after_script:
  - cat regression.diffs

notifications:
  email:
    on_success: change
    on_failure: always
